
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS MapModel();
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS entityShortId text UNIQUE;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS altitude text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS rotation text[];

CREATE TABLE IF NOT EXISTS Airport();
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS entityShortId text UNIQUE;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS altitude text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS rotation text[];
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS codeIATA text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS codeICAO text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE Airport ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);

CREATE TABLE IF NOT EXISTS Airline();
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS entityShortId text UNIQUE;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS altitude text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS rotation text[];
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS callSign text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS codeIATA text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS codeICAO text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE Airline ADD COLUMN IF NOT EXISTS source text;

CREATE TABLE IF NOT EXISTS Aircraft();
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS entityShortId text UNIQUE;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS altitude text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS rotation text[];
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS timeZone text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS airportId text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS departureDate timestamp with time zone;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS arrivalDate timestamp with time zone;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS avgSpeedInMph decimal;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS belongsToAircraftModel text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS dateIssued text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS heading decimal;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS isOnGround boolean;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS registration text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS speed decimal;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS verticalSpeed decimal;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS path path;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS simulation boolean;
ALTER TABLE Aircraft ADD COLUMN IF NOT EXISTS simulationDelayMillis bigint;

CREATE TABLE IF NOT EXISTS Contract();
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS region text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS abbreviation text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS contractId text UNIQUE;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS startDate timestamp with time zone;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS investmentYearsTotal integer;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS investmentYears integer[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS investmentsPerYear decimal[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS investmentsPerYearCumulative decimal[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS assetClasses text[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS assetClassesTargetIrr decimal[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS revenueStreams text[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS economicOutputProjections decimal[];
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS totalGdpImpact decimal;
ALTER TABLE Contract ADD COLUMN IF NOT EXISTS economicOutputProjectionsDataset jsonb;

DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'aircraft_airportid_airport_fkey') THEN ALTER TABLE Aircraft ADD CONSTRAINT aircraft_airportid_airport_fkey FOREIGN KEY(airportId) REFERENCES Airport(entityShortId); END IF; END $$;
