apiVersion: v1
kind: Service
metadata:
  namespace: smartaeronautics
  name: smartaeronautics
  labels:
    app.kubernetes.io/instance: smartaeronautics
    app.kubernetes.io/name: smartaeronautics
spec:
  ports:
  - name: http
    port: 10250
    protocol: TCP
    targetPort: 10250
  - name: cluster
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    app: smartaeronautics
    app.kubernetes.io/instance: smartaeronautics
    app.kubernetes.io/name: smartaeronautics
    deployment: smartaeronautics
  type: ClusterIP
